name = "cloud-mail"
main = "src/index.js"
compatibility_date = "2025-06-04"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[[d1_databases]]
binding = "db"
database_name = "cloud-mail"
database_id = "7134ccc4-32bb-4301-b228-a2a0ba17466e"

[[kv_namespaces]]
binding = "kv"
id = "6950080c853341ba865383735bec68e1"

[ai]
binding = "ai"

[assets]
binding = "assets"
directory = "./dist"
not_found_handling = "single-page-application"
run_worker_first = true

[vars]
domain = ["miku01.de", "mikus.us.ci", "aloneowo.cc.cd", "aloneowo.de5.net", "hatsune01.top", "hatsune01.de"]
admin = "aloneowo@miku01.de"
jwt_secret = "98157da26ac18f2462cebdb1442d2cfd5cc59f4b71c36148f8e3d171ea414dca"

[build]
command = "pnpm --prefix ../mail-vue install && pnpm --prefix ../mail-vue run build"
